run:
  timeout: 30m
  modules-download-mode: readonly
  skip-files:
    - ".*_test.go$"  #  ignore test files
    - ".*_gen.go$"   #  ignore generated files ending in _gen.go
    - ".*\\.gen.go$" #  ignore generated files ending in .gen.go

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - gomnd
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nestif
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
